version: "3.8"

services:
  zipper:
    image: zipper-api:25.10.27
    name: zipper
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build             # force build instead of pull in standalone
    environment:
      - BASE_DIR=/data
      - OUT_DIR=/output
      - API_TOKEN_FILE=/run/secret/token
    ports:
      - "3256:3256"
    volumes:
      - /srv/assistant/assistant-zipper/in:/data:ro
      - /srv/assistant/assistant-zipper/out:/output:rw
      - /srv/assistant/assistant-zipper/secret/token:/run/secret/token:ro
    restart: unless-stopped
